config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  root 'welcome#home'

  devise_for :users

  namespace :admin, path: 'fiddle' do
    root 'dashboard#home'
    authenticate :user do
      mount Sidekiq::Web => '/jobs'
    end

    resources :products, only: [:index, :show, :edit, :update]

    get 'export/catalog(/:file_suffix)', to: 'export#catalog', as: :export_catalog

    resources :report_tasks, only: :create do
      member { get :enqueue }
    end

    get 'wide-syncs', to: 'wide_sync_jobs#index', as: :wide_syncs
    get 'narrow-syncs', to: 'narrow_sync_jobs#index', as: :narrow_syncs
  end
end

app/views/admin/home.slim
.one
  h1= "Welcome, #{@user.name}"

  = link_to 'Страница товаров Женская', :admin_wide_syncs
  br
  = link_to 'Страница товаров Платья', :admin_narrow_syncs

  p
    | Всего товаров (включая недоступные)
    strong=< number_with_delimiter @products_count, delimiter: ' '

  - if @latest_updated_product
    p
      | Last update
      strong=< l @latest_updated_product.updated_at, format: :succinct

  .something
    = link_to admin_export_catalog_path('succinct.xlsx'), target: :_blank do
      .link
        .image 🌭
        .text
          .title Download old report
          .description= file_description('succinct.xlsx')


  h2= t '.reports_creating'

  = form_for :daily_report_task, url: { action: :create, controller: :report_tasks }, class: 'daily-report-form' do |f|
    .something
      | С
      = f.date_field(:start_at, class: 'field')
      | по
      = f.date_field(:end_at, class: 'field')
      = f.hidden_field(:type, value: 'DailyReportByHourTask')
      = f.submit t('.create_report_by_hour')

  .line

  h2= t '.reports'

  ul.something
    - @tasks.each do |task|
      li.link
        - if task.status == 'completed'
          .image 🍹
        - else
          .status(class=task.status)= t "daily_report_task.statuses.#{task.status}"
        - if task.status == 'dequeued'
          .status.enqueue= link_to '🔃', enqueue_admin_report_task_path(task)
        .text
          .title
            - title = t("task_title.#{task.type}") + ": #{task.start_at} - #{task.end_at}"
            - if task.status == 'completed'
              - task.filenames.each do |filename|
                - basename = File.basename(filename)
                = link_to basename, admin_export_catalog_path(basename), target: :_blank
                .description= file_description(basename)
            - else
              = title


  .line

  h2 Tables in Database

  ul.something
    - @tables.each do |db_table|
      p= "#{db_table['relation']} => #{db_table['total_size']}"